<?

unset($t);
session_start();

//-------------
function admin() 
{
   global $hostname, $enter, $t, $SID, $login, $pass;

   $enter="нет";
 
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "mysql";
   $usertable = "user"; 

   /* создать соединение */
   $conect=@mysql_connect($hostname,$login,$pass);
   if ($conect!="false") 
   { 
      //выбираем БД
      @mysql_select_db("$dbName");
      $query="select * from $usertable";
      //делаем запрос в mysql
      $f=@mysql_query($query);
      $y=@mysql_num_rows($f); 
      unset($enter);   
   
      for ($i=0; $i<$y; $i++) 
      {     
         $a[]=convert_cyr_string(@mysql_result($f,$i,1),"d","w");
         $a[]=convert_cyr_string(@mysql_result($f,$i,6),"d","w");
         if (($a[0]==$login)&($a[1]=="Y")) 
         {
            $enter="да";    
            break;
         }
         unset($a);
      }  
      @mysql_close();

      if ($enter=="да")
      {
         //exit(header("Location: ?c=nazad&SID=$SID"));
         ?>   <center><table border=2><td BGCOLOR=white>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <a href= ?c=tov&SID=$SID>Данные о товаре</a>&nbsp;&nbsp;&nbsp;&nbsp;
              &nbsp;&nbsp;&nbsp;</td><td BGCOLOR=white>&nbsp;&nbsp;&nbsp;
              &nbsp;&nbsp;&nbsp;
              <a href= ?c=zakaz&SID=$SID>Данные о заказах</a>&nbsp;
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td BGCOLOR=white>
              &nbsp;&nbsp;&nbsp;
              <a href= ?c=infop&SID=$SID>Данные о покупателях</a>&nbsp;
              &nbsp;&nbsp;</td><td BGCOLOR=white>
              &nbsp;&nbsp;&nbsp;
              <a href= ?c=infoskid&SID=$SID>Данные о скидках</a>&nbsp;
              &nbsp;&nbsp;</td></table></center><br><br>

              <center><table border=2><td BGCOLOR=white>&nbsp;
              <a href= ?c=dob&SID=$SID>Добавление данных в БД</a>&nbsp;</td>
              <td BGCOLOR=white>&nbsp;<a href= ?c=uvel&SID=$SID>Увеличение кол-ва товара
              </a>&nbsp;</td></table></center>
         <?         
      }else echo "<br><br><br><br><center><h2>Введен неверный логин или пароль!!!</h2></center>";


   }else echo "<br><br><br><br><center><h2>Введен неверный логин или пароль!!!</h2></center>";

}
//-------------


//-------------
function infotov()
{
   global $ogl_tov, $t, $SID, $hostname, $coltab;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "tovar"; 
 
   /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");
   $query="select * from $usertable";
   //делаем запрос в mysql
   $f=mysql_query($query);

   $x=count($ogl_tov);          // вычисляем число колонок
   $y=mysql_num_rows($f);   // и число строк
   echo "<center><table border=2><tr>";
   // рисуем заголовок таблицы   
   for ($j=0; $j<$x; $j++) 
   {
      if (strlen($ogl_tov[$j])==0) echo "<th BGCOLOR=$coltab>&nbsp;</th>";
      else echo "<th BGCOLOR=$coltab>$ogl_tov[$j]</th>";
   }
echo "<th BGCOLOR=$coltab>&nbsp;</th>";
   echo "</tr>";
   // основной цикл вывода данных о покупателях
   for ($i=0; $i<$y; $i++) 
   {     
     $a[]=$i+1;
     $a[]=convert_cyr_string(mysql_result($f,$i,1),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,2),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,3),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,4),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,5),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,6),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,7),"d","w"); 
     $a[]=convert_cyr_string(mysql_result($f,$i,9),"d","w");           
     echo "<tr ALIGN=center>";
     // цикл вывода всех колонок текущей строки таблицы
     for ($j=0; $j<$x-1; $j++) 
     {
         // если ячейка пустая, там надо поместить "&nbsp;";
         if (strlen($a[$j])==0) echo "<td BGCOLOR=$coltab>&nbsp;</td>";
         else echo "<td BGCOLOR=$coltab>$a[$j]</td>";
     }     

$id=mysql_result($f,$i,0);
echo "<td BGCOLOR=$coltab><a href=$PHP_SELF?c=asort&id=$id&SID=$SID>$a[$j]</a></td>";
echo "<td BGCOLOR=$coltab><a href=$PHP_SELF?c=del&id=$id&SID=$SID>удалить</a></td>";
     echo "</tr>";
     unset($a);
   }
   echo "</table></center>";
   mysql_close();
}
//-------------



//-------------
function zakaz()
{
   global $ogl_zak, $t, $SID, $hostname, $coltab;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "zakaz"; 
 
   /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");
   $query="select * from $usertable";

   //делаем запрос в mysql
   $f=mysql_query($query);

   $x=count($ogl_zak);      // вычисляем число колонок
   $y=mysql_num_rows($f);   // и число строк

   echo "<center><table border=2><tr>";
   // рисуем заголовок таблицы   
   for ($j=0; $j<$x; $j++) 
   {
      if (strlen($ogl_zak[$j])==0) echo "<th BGCOLOR=$coltab>&nbsp;</th>";
      else echo "<th BGCOLOR=$coltab>$ogl_zak[$j]</th>";
   }
   echo "</tr>";

   // основной цикл вывода данных о заказах
   for ($i=0; $i<$y; $i++) 
   {      
      $a[]=convert_cyr_string(mysql_result($f,$i,0),"d","w");     
      $a[]=convert_cyr_string(mysql_result($f,$i,1),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,2),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,3),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,4),"d","w");     
      $a[]=convert_cyr_string(mysql_result($f,$i,5),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,10),"d","w");

      $query="select naim_org, fam from pokup where id=$a[1]";
      $f2=mysql_query($query);

      $b[]=convert_cyr_string(mysql_result($f2,0,0),"d","w");
      $b[]=convert_cyr_string(mysql_result($f2,0,1),"d","w");     

      $query="select id_tov, kol_tov, summa, skid from dopoln where id_zak=$a[0]";
      $f3=mysql_query($query);
      $y3=mysql_num_rows($f3);     
     
      // цикл вывода всех колонок текущей строки таблицы
            
      for ($k=0; $k<$y3; $k++)
      {
         echo "<tr ALIGN=center>";
         echo "<td BGCOLOR=$coltab>$a[0]</td>";
         if ($k==0) 
         {
              
            echo "<td BGCOLOR=$coltab>$a[1]</td>".
                 "<td BGCOLOR=$coltab>$b[0]</td>".
                 "<td BGCOLOR=$coltab>$b[1]</td>";                  
         }
         else
         {
            echo "<td BGCOLOR=$coltab>-</td>".                    
                 "<td BGCOLOR=$coltab>-</td>".
                 "<td BGCOLOR=$coltab>-</td>";
         }

         $c[]=convert_cyr_string(mysql_result($f3,$k,0),"d","w");
         $c[]=convert_cyr_string(mysql_result($f3,$k,1),"d","w"); 
         $c[]=convert_cyr_string(mysql_result($f3,$k,2),"d","w");                    
         $c[]=convert_cyr_string(mysql_result($f3,$k,3),"d","w");                    
 
         $query="select naim, cena from tovar where id=$c[0]";
         $f4=mysql_query($query);
         $d[]=convert_cyr_string(mysql_result($f4,0,0),"d","w");
         $d[]=convert_cyr_string(mysql_result($f4,0,1),"d","w");
  
         echo "<td BGCOLOR=$coltab>$d[0]</td>".
              "<td BGCOLOR=$coltab>$d[1]</td>".              
              "<td BGCOLOR=$coltab>$c[1]</td>".              
              "<td BGCOLOR=$coltab>$c[2]</td>";
 
         if ($k==0) 
         {
            echo "<td BGCOLOR=$coltab>$a[4]</td>".
                 "<td BGCOLOR=$coltab>$c[3]</td>".              
                 "<td BGCOLOR=$coltab>$a[5]</td>".
                 "<td BGCOLOR=$coltab>$a[2]</td>".
                 "<td BGCOLOR=$coltab>$a[3]</td>".
                 "<td BGCOLOR=$coltab>$a[6]</td>";
         }
         else
         {
            echo "<td BGCOLOR=$coltab>-</td>".
                 "<td BGCOLOR=$coltab>-</td>".
                 "<td BGCOLOR=$coltab>-</td>".
                 "<td BGCOLOR=$coltab>-</td>".
                 "<td BGCOLOR=$coltab>-</td>".
                 "<td BGCOLOR=$coltab>&nbsp;</td>";
         }
         echo "</tr>";
         unset($c);
         unset($d);
      }             
     
      unset($a);
      unset($b);
     
   }
   echo "</table></center>";
   mysql_close();
}
//-------------



//-------------
function infop()
{
   global $ogl, $t, $SID, $hostname, $coltab;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "pokup"; 
 
   /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");
   $query="select * from $usertable";
   //делаем запрос в mysql
   $f=mysql_query($query);

   $x=count($ogl);          // вычисляем число колонок
   $y=mysql_num_rows($f);   // и число строк
   echo "<center><table border=2><tr>";
   // рисуем заголовок таблицы   
   for ($j=0; $j<$x; $j++) 
   {
      if (strlen($ogl[$j])==0) echo "<th BGCOLOR=$coltab>&nbsp;</th>";
      else echo "<th BGCOLOR=$coltab>$ogl[$j]</th>";
   }
   echo "</tr>";
   // основной цикл вывода данных о покупателях
   for ($i=0; $i<$y; $i++) 
   {     
      $a[]=$i+1;
      $a[]=convert_cyr_string(mysql_result($f,$i,1),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,2),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,3),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,4),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,5),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,6),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,7),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,8),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,9),"d","w");
      if (count($a)<2) continue; // если она пустая (глюки), пропускаем
      echo "<tr ALIGN=center>";
      // цикл вывода всех колонок текущей строки таблицы
      for ($j=0; $j<$x; $j++) 
      {
         // если ячейка пустая, там надо поместить "&nbsp;";
         if (strlen($a[$j])==0) echo "<td BGCOLOR=$coltab>&nbsp;</td>";
         else echo "<td BGCOLOR=$coltab>$a[$j]</td>";
      }     
      echo "</tr>";
      unset($a);
   }
   echo "</table></center>";
   mysql_close();
}
//-------------



//-------------
function dob()
{
   global $ogl_t2, $t, $SID, $hostname, $coltab, $v;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "tovar"; 
 
   /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");

   for ($i=0; $i<10; $i++)
   { 
      $v2[]=convert_cyr_string($v[$i],"w","d");
   }

   $query="insert into $usertable set naim='$v2[0]', articul='$v2[1]', prihod='$v2[2]', kol_vo='$v2[3]', rezerv='$v2[4]', nacenka='$v2[5]', cena='$v2[6]', info='$v2[7]', asort='$v2[8]', pict='$v2[9]'";
   //делаем запрос в mysql
   $f=mysql_query($query); 

   mysql_close();
}
//-------------



//-------------
function delete($id)
{
   global $t, $hostname;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "tovar"; 

 /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");

   $query="delete from $usertable where id=$id";
   $f=mysql_query($query);
   mysql_close();
}
//-------------




//-------------
function asortiment($id)
{
   global $t, $hostname;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "tovar"; 

 /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");

   $query="select asort from $usertable where id=$id";
   $f=mysql_query($query);
   $as=convert_cyr_string(mysql_result($f,0,0),"d","w");
   if ($as=='Y') $as='N';
   else $as='Y';
   $query="update $usertable set asort='$as' where id=$id";   
   $f=mysql_query($query);
   mysql_close();
}
//-------------



//-------------
function sure($s)
{   
   global $id;
   echo "<form action=$PHP_SELF?c=$s&SID=$SID&id=$id method=POST>".
        "<br><br><br><br><br><br><br><br>".
        "<h2><center><font color=red><b>ВЫ УВЕРЕНЫ?</b></font></center></h2>".
        "<center><input type=submit name=da value='ДА'> &nbsp;".
        "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".
        "<input type=submit name=net value='НЕТ'></center></form>";
}
//-------------



//-------------
function uvel()
{   
   global $ogl_tov, $t, $SID, $hostname, $coltab, $id;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "tovar"; 
 
   /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");
   $query="select * from $usertable";
   //делаем запрос в mysql
   $f=mysql_query($query);

   $y=mysql_num_rows($f);   // и число строк

   echo "<form action=$PHP_SELF?c=izm&SID=$SID&v=$v method=POST>";
   echo "<center><table border=2><tr>";
   // рисуем заголовок таблицы   
   
   echo "<th BGCOLOR=$coltab>$ogl_tov[0]</th>";
   echo "<th BGCOLOR=$coltab>$ogl_tov[1]</th>";
   echo "<th BGCOLOR=$coltab>$ogl_tov[2]</th>";
   echo "<th BGCOLOR=$coltab>$ogl_tov[4]</th>";
   echo "<th BGCOLOR=$coltab>&nbsp;</th>";
   echo "<th BGCOLOR=$coltab>$ogl_tov[4]</th>";
   //echo "<th BGCOLOR=$coltab>&nbsp;</th>";
   echo "</tr>";

   // основной цикл вывода данных о покупателях
   for ($i=0; $i<$y; $i++) 
   {     
     $a[]=$i+1;
     $a[]=convert_cyr_string(mysql_result($f,$i,1),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,2),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,4),"d","w");
           
     echo "<tr ALIGN=center>";
     // цикл вывода всех колонок текущей строки таблицы
     for ($j=0; $j<count($a); $j++) 
     {
         // если ячейка пустая, там надо поместить "&nbsp;";
         if (strlen($a[$j])==0) echo "<td BGCOLOR=$coltab>&nbsp;</td>";
         else echo "<td BGCOLOR=$coltab>$a[$j]</td>";
     }     

     $id=mysql_result($f,$i,0);

     echo "<td BGCOLOR=$coltab>+</td>".
          "<td BGCOLOR=$coltab>".
          "<input size=4 type=text name=v[$id]></td></tr>";
     unset($a);
   }
   echo "</table><input type=submit value='Добавить товар'></center></form>";
   mysql_close();
}
//-------------



//------------- Изменение количества товара
function izmkol()
{
   global $t, $hostname, $v;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "tovar"; 

 /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");

$k=@array_keys($v);
for ($i=0; $i<count($k); $i++) 
{
         $id=$k[$i];


   $query="select kol_vo from $usertable where id='$id'";
   $f=mysql_query($query);

   $kol=mysql_result($f,0,0);
   if ($v[$id]=='') $v[$id]=0;
   $kol+=$v[$id];

   $query="update $usertable set kol_vo='$kol' where id='$id'";   
   $f=mysql_query($query);
}
   mysql_close();
}
//-------------




//------------- Информация о скидках
function insk()
{
   global $t, $hostname, $ogl_sk, $coltab;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "skid"; 

 /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");

   $query="select * from $usertable";
   $f=mysql_query($query);

   echo "<center><table border=2><tr>";
   for ($j=0; $j<count($ogl_sk); $j++) 
   {
      // если ячейка пустая, там надо поместить "&nbsp;";
      if (strlen($ogl_sk[$j])==0) echo "<th BGCOLOR=$coltab>&nbsp;</th>";
      echo "<th BGCOLOR=$coltab>$ogl_sk[$j]</th>";
   }
   echo "<th BGCOLOR=$coltab>&nbsp;</th>";
   $y=mysql_num_rows($f);   

   for ($i=0; $i<$y; $i++) 
   {     
      $a[]=$i+1;
      $a[]=convert_cyr_string(mysql_result($f,$i,1),"d","w");
      $a[]=convert_cyr_string(mysql_result($f,$i,2),"d","w");
     
      if (count($a)<2) continue; // если она пустая (глюки), пропускаем
      echo "<tr ALIGN=center>";
      // цикл вывода всех колонок текущей строки таблицы
      for ($j=0; $j<count($ogl_sk); $j++) 
      {
         // если ячейка пустая, там надо поместить "&nbsp;";
         if (strlen($a[$j])==0) echo "<td BGCOLOR=$coltab>&nbsp;</td>";
         else echo "<td BGCOLOR=$coltab>$a[$j]</td>";
      }  
   
      $id=mysql_result($f,$i,0);
      echo "<td BGCOLOR=$coltab><a href=$PHP_SELF?c=delsk&id=$id&SID=$SID>удалить</a></td>";
      echo "</tr>";
      unset($a);
   }
   echo "</table></center><br>";


   echo "<form action=$PHP_SELF?c=dobvsk&SID=$SID&v1=$v1&v2=$v2 method=POST>".
        "<center><table border=2><tr>".
        "<th BGCOLOR=$coltab>Более</th>".
        "<td><input type=text size=7 name='v1'></td>".
        "<th BGCOLOR=$coltab>Скидка</th>".
        "<td><input type=text size=7 name='v2'></td>".
        "<td><input type=submit value='Добавить'></td>".
        "</tr></table></center></form>"; 
 
   mysql_close(); 
}
//-------------



// Удаление строки из таблицы skid
//-------------
function dlsk($id)
{
   global $t, $hostname;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "skid"; 

   /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");

   $query="delete from $usertable where id=$id";
   $f=mysql_query($query);
   mysql_close();
}
//-------------




// Добавление строки в таблицу skid       
//-------------
function dbsk($v1,$v2)
{
   global $t, $hostname;
   $username = $t[0][log];
   $password = $t[0][pas];
   $dbName = "shop";
   $usertable = "skid"; 

   /* создать соединение */
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");

   $query="insert into $usertable set svishe='$v1', skid='$v2'";
   $f=mysql_query($query);
   mysql_close();
}
//-------------


$ogl=array(
   "№", "Наим. организации", "Фамилия", "Имя",
   "Отчество", "Юр. адрес", "Факт. адрес", "ИНН",
   "Телефон", "E-mail");

$ogl_zak=array(
   "№ зак", "№ пок", "Наим. орг", "Фамилия", "Наим. тов.",
   "Цена тов.", "Кол. тов.", "Сумма", "ИТОГО:", "Скидка (в %)",
   "ИТОГО(со скидкой):", "Дата заказа", "Время заказа", "Доставлен?");

$ogl_tov=array(
   "№", "Наименование", "Артикул", "Приход(в руб)", "Кол-во(шт)",
   "Резерв(шт)", "Наценка(%)", "Цена(в руб)", "В ассортименте?");

$ogl_t2=array(
   "Наименование", "Артикул", "Приход(в руб)", "Кол-во(шт)",
   "Резерв(шт)", "Наценка(%)", "Цена(в руб)", "Информация",
   "Есть в ассортименте?", "Путь к рисунку");

$ogl_sk=array(
   "№", "Более (в руб)", "Скидка (в %)");


$hostname = "localhost";
$coltab='#eeeedd';
$col='#eeeeee';



//--------------------------------------------------//
//------------- основной код модуля admin ----------//
//--------------------------------------------------//

// $c - основная переменная, указывающая на нужное действие
if (!isset($c)) 
{
   $c='';
   // Очистка массива $t
   $k=@array_keys($t);
   for ($i=0; $i<count($k); $i++) 
   {
      unset($t[$k[$i]]);      
   }
}

switch($c) 
{

   // без параметров 
   case "":   
      echo "<TITLE>Ввод пароля</TITLE>";
      
      echo "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td>".
           "</table><hr><br><br><br><center>".
           "<FONT color=#9999dd size=5>Введите пароль!".
           "</FONT></center><br><br><br><br>";

      ?>
           <center><TABLE WIDTH = 400><TR><TD align = center>
           <form action= ?c=adm&SID=$SID&login=$login&pass=$pass method=POST>Логин:<BR>
           <input type="text" NAME="login" SIZE="15"><BR>Пароль:<BR>
           <input type="password" NAME="pass" SIZE="15">
           <br><input type="submit" VALUE="Вход!">
           </form></td></tr></TABLE></center>
      <?
      
   break;


   case "adm":   
      echo "<TITLE>Администраторская</TITLE>";
      
      $t[0][log]=$login;
      $t[0][pas]=$pass;
       
      session_register("t");

      echo "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;&nbsp;&nbsp;&nbsp;<a href= ?c=&SID=$SID>Ввод пароля</a>".
           "&nbsp;&nbsp;&nbsp;&nbsp;</td></table><hr><br><br><br><center>".
           "<FONT color=#9999dd size=5>Администраторская".
           "</FONT></center><br><br>";
      admin();
   break;



   case "nazad":   
      echo "<TITLE>Администраторская</TITLE>".
           "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;&nbsp;&nbsp;&nbsp;<a href= ?c=&SID=$SID>Ввод пароля</a>".
           "&nbsp;&nbsp;&nbsp;&nbsp;</td>".
           "</table><hr><br><br><br><center>".
           "<FONT color=#9999dd size=5>Администраторская".
           "</FONT></center><br>";

      ?>   <center><table border=2><td BGCOLOR=white>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <a href= ?c=tov&SID=$SID>Данные о товаре</a>&nbsp;&nbsp;&nbsp;&nbsp;
           &nbsp;</td><td BGCOLOR=white>&nbsp;&nbsp;&nbsp;&nbsp;
           &nbsp;<a href= ?c=zakaz&SID=$SID>Данные о заказах</a>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td BGCOLOR=white>
           &nbsp;&nbsp;&nbsp;<a href= ?c=infop&SID=$SID>
           Данные о покупателях</a>&nbsp;&nbsp;&nbsp;</td>
           <td BGCOLOR=white>&nbsp;&nbsp;&nbsp;
           <a href= ?c=infoskid&SID=$SID>Данные о скидках</a>&nbsp;
           &nbsp;&nbsp;</td></table></center><br><br>

           <center><table border=2><td BGCOLOR=white>&nbsp;
           <a href= ?c=dob&SID=$SID>Добавление данных в БД</a>&nbsp;</td>
           <td BGCOLOR=white>&nbsp;
           <a href= ?c=uvel&SID=$SID>Увеличение кол-ва товара</a>&nbsp;</td></center>
      <?
   break;


   // Данные о товаре
   case "tov":
      echo "<TITLE>Данные о товаре</TITLE>".           
           "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;<a href= ?c=nazad&SID=$SID>Администраторская</a>&nbsp;".
           "</td></table><hr><center><FONT color=#9999dd size=5>".
           "Данные о товаре</FONT></center><br>";
      infotov();
   break;


   case "zakaz":  
      echo "<TITLE>Данные о заказах</TITLE>".           
           "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=#eeeedd>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;<a href= ?c=nazad&SID=$SID>Администраторская</a>&nbsp;".
           "</td></table><hr><center><FONT color=#9999dd size=5>".
           "Данные о заказах</FONT></center><br>";
      zakaz();
   break;  


   // Выводится ИНФормация О Покупателях из таблицы "pokup"
   case "infop":  
      echo "<TITLE>Данные о покупателях</TITLE>".           
           "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=#eeeedd>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;<a href= ?c=nazad&SID=$SID>Администраторская</a>&nbsp;".
           "</td></table><hr><center><FONT color=#9999dd size=5>".
           "Данные о покупателях</FONT></center><br>";
      infop();
   break;  


   // Информация о скидках
   case "infoskid":
      echo "<TITLE>Данные о скидках</TITLE>".           
           "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=#eeeedd>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;<a href= ?c=nazad&SID=$SID>Администраторская</a>&nbsp;".
           "</td></table><hr><center><FONT color=#9999dd size=5>".
           "Данные о скидках</FONT></center><br>";
      insk();      
   break;


   // Добавление данных в БД
   case "dob":
      echo "<TITLE>Добавление данных в БД</TITLE>".           
           "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;<a href= ?c=nazad&SID=$SID>Администраторская</a>&nbsp;".
           "</td></table><hr><center><FONT color=#9999dd size=5>".
           "Добавление данных в БД</FONT></center><br>";

      echo "<center><form action='$PHP_SELF?c=dobpov&SID=$SID&v=$v' method=post>".
           "<table border=1>";
      for ($i=0; $i<count($ogl_t2); $i++) 
      {
         echo "<tr><td BGCOLOR=$coltab>$ogl_t2[$i]</td>".
              "<td><input type=text size=32 name='v[$i]'></td></tr>";
      }
      echo "</table>";

      echo "<input type=submit value='Добавить'>".
           "</form></center>";

      
   break;


   case "dobpov":
      dob();
      exit(header("Location: $PHP_SELF?c=nazad&SID=$SID"));
   break;


   case "del":      
      if ((!isset($da))&&(!isset($net)))
      {
         echo "<BODY BGCOLOR=$col>";
         sure("del");         
      }
      if (isset($da))
      {
         delete($id);
         exit(header("Location: $PHP_SELF?c=tov&SID=$SID"));
      }
      if(isset($net)) exit(header("Location: $PHP_SELF?c=tov&SID=$SID"));
      unset($da);
      Unset($net);
   break;


   case "asort":
      asortiment($id);
      exit(header("Location: $PHP_SELF?c=tov&SID=$SID"));
   break;


   case "uvel":
      echo "<TITLE>Увеличение количества товара</TITLE>".           
           "<BODY BGCOLOR=$col alink=blue vlink=blue>".
           "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href=\>".
           "Главная страница</a>&nbsp;&nbsp;</td><td BGCOLOR=$coltab>".
           "&nbsp;<a href= ?c=nazad&SID=$SID>Администраторская</a>&nbsp;".
           "</td></table><hr><center><FONT color=#9999dd size=5>".
           "Увеличение количества товара</FONT></center><br>";
      Uvel();
   break;


   // Изменение количества товара
   case "izm":
      izmkol();
      exit(header("Location: $PHP_SELF?c=uvel&SID=$SID"));
   break;


   // Удаление строки из таблицы skid
   case "delsk":
      if ((!isset($da))&&(!isset($net)))
      {
         echo "<BODY BGCOLOR=$col>";
         sure("delsk");         
      }
      if (isset($da))
      {
         dlsk($id);
         exit(header("Location: $PHP_SELF?c=infoskid&SID=$SID"));
      }
      if(isset($net)) exit(header("Location: $PHP_SELF?c=infoskid&SID=$SID"));
      unset($da);
      Unset($net);      
   break;


   // Добавление строки в таблицу skid
   case "dobvsk":
      dbsk($v1,$v2);
      exit(header("Location: $PHP_SELF?c=infoskid&SID=$SID"));      
   break;


}

?>