<?

unset($t);
session_start();

/* функция прибавляет в корзину новый товар, где $n - это номер строки
   в БД MySQL. Далее, в сессиях сохраняется не номер строки, а число
   ID и используется повсеместно. Если товар уже 
   существует, то корзина никак не меняется.   */

//-------------
function tadd($n) 
{   
   global $t, $hostname, $username, $password, $dbName, $usertable;
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");
   $query="select * from $usertable";
   $f=mysql_query($query);

   $id=mysql_result($f,$n,0);
   if (isset($t[all][$id])) return; // если товар уже в корзине - выход

   $t[all][$id]=$id;    // флаг, определяющий что товар уже есть в корзине
   //достаём наименование из БД
   $t[$id][name]=convert_cyr_string(mysql_result($f,$n,1),"d","w");
   $t[$id][cena]=mysql_result($f,$n,7);
//$t[$id][skid]=mysql_result($f,$n,3);
   $t[$id][sklad]=mysql_result($f,$n,4);
   $t[$id][info]=mysql_result($f,$n,8);
   $t[$id][kol]=1;      // кол-во в начале равно "1 штуке"

   session_register("t"); // записали переменную в сессию
   mysql_close();
}
//-------------

//------------- Рисует таблицу с товарами в корзине. 
function korzina() 
{
   global $t, $PHP_SELF, $SID, $ogl, $coltab, $F_sklad, $skid, $summ2;
   global $summ, $sm;
   // проходим массив $t[all] по списку его ключей
   $k=@array_keys($t[all]);
   if (count($k)>0)
   {      
      echo "<br><FONT color=red>КОЛИЧЕСТВО</FONT> товара ".
           "не вводите больше чем есть на складе!!!  ".
           "(при изменении количества нажмите 'внести изменения')";
      echo "<br><FONT color=red>~</FONT> -приближённое значение (скидка считается от общей суммы заказа)";
      echo "<form action=$PHP_SELF?c=kolvo&SID=$SID method=POST>".
        // рисуем заголовок таблицы с корзиной:
           "<table border=2><tr align=center><th BGCOLOR=$coltab>$ogl[0]</th>".
           "<th BGCOLOR=$coltab>$ogl[1]</th>".
           "<th BGCOLOR=$coltab>На складе</th>".
           "<th BGCOLOR=$coltab>$ogl[2]</th>".
           "<th BGCOLOR=$coltab>$ogl[3]</th>".
           "<th BGCOLOR=$coltab>Кол-во</th>".
           "<th BGCOLOR=$coltab>Сумма(в руб)</th>".
           "<th BGCOLOR=$coltab>Сумма со скидкой(в руб)</th>".
           "<th BGCOLOR=$col>&nbsp</th></tr>";    
$n=1;  
      for ($i=0; $i<count($k); $i++) 
      {
         $id=$k[$i];
         $S=$t[$id][cena]*$t[$id][kol];
         $sk=$t[$id][cena]/100*$skid;
         $sk=$t[$id][cena]-$sk;

//Округление до сотых
$sk=$sk*100;
$sk=round($sk)/100;

         $Ssk=$sk*$t[$id][kol];

//Округление до сотых
$Ssk=$Ssk*100;
$Ssk=round($Ssk)/100;

         echo "<tr align=center><td BGCOLOR=$coltab>$n</td>".
              "<td BGCOLOR=$coltab>{$t[$id][name]}</td>".
              "<td BGCOLOR=$coltab>{$t[$id][sklad]}</td>".
              "<td BGCOLOR=$coltab>{$t[$id][cena]}</td>".         
              "<td BGCOLOR=$coltab>~ $sk</td>".
              "<td BGCOLOR=$coltab>".
              "<input size=4 type=text name=v[$id] value={$t[$id][kol]}></td>".
              "<td BGCOLOR=$coltab>{$S}</td>".
              "<td BGCOLOR=$coltab>~ $Ssk</td>".
              "<td BGCOLOR=$col>".
              "<a href=$PHP_SELF?c=del&id=$id&SID=$SID>удалить</a></td></tr>";
         $n=$n+1;
      }

      echo "<tr align=center><td BGCOLOR=$coltab>&nbsp;</td>".
           "<th BGCOLOR=$coltab>ИТОГО:</th>".
           "<td BGCOLOR=$coltab>&nbsp;</td>".
           "<td BGCOLOR=$coltab>&nbsp;</td>".         
           "<td BGCOLOR=$coltab>&nbsp;</td>".
           "<td BGCOLOR=$coltab>$summ2</td>".
           "<td BGCOLOR=$coltab>$summ</td>".
           "<th BGCOLOR=$coltab>".sprintf("<FONT color=red>%.2f</FONT>",$sm)."</th>".
           "<td BGCOLOR=$col>&nbsp;</td></tr>"; 

      // внизу таблицы две кнопки:
      //   Измениения - сохранить изменение числа товаров и обновить страницу
      //   Заказ - сохр. изм. + перейти на страницу оформления заказа
      echo "</table><center><input type=submit name=zakaz value='Оформить заказ'> &nbsp;".
           "&nbsp;<input type=submit name=edit value='Внести изменения'></center></form>";

      echo "<a href='$PHP_SELF?c=delete&SID=$SID'>Очистить корзину!</a><br>";
           
    }else echo "<br><br><br>КОРЗИНА ПУСТАЯ<br><br><br>";
}
//-------------

/* Выводит на экран таблицу с товарами. В таблице автоматом генериться новая
   колонка с checkbox'асами, отметив которые и нажав "добавив", можно
   занести товары в корзину.   */

//-------------
function price() 
{
   global $t, $PHP_SELF, $SID, $ogl, $coltab, $skid;
   global $hostname, $username, $password, $dbName, $usertable;
   //конектимся с mysql
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   //выбираем БД
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");
   $query="select naim, cena, kol_vo, asort from $usertable";
   //делаем запрос в mysql
   $f=mysql_query($query);

   $x=count($ogl);          // вычисляем число колонок
   $y=mysql_num_rows($f);   // и число строк   
   echo "<center>";   
   // форма (не забываем вписать $SID) + начало таблицы:
   echo "<form action=$PHP_SELF method=POST><input type=hidden name=c value=add>".
        "<input type=hidden name=SID value='$SID'><table border=2>";
   // рисуем заголовок таблицы
   echo "<tr>";
   for ($j=0; $j<$x; $j++) 
   {
      if (strlen($ogl[$j])==0) echo "<th BGCOLOR=$coltab>&nbsp;</th>";
      else echo "<th BGCOLOR=$coltab>$ogl[$j]</th>";
   }
   // рисуем колонку просмотр
   echo "<th BGCOLOR=$coltab>&nbsp;</th>";

   // рисуем колонку, где будут checkbox'ы
   echo "<th BGCOLOR=$coltab> ' x ' </th></tr>";

$n=1;
   // основной цикл вывода прайса
   for ($i=0; $i<$y; $i++) 
   {

$as=convert_cyr_string(mysql_result($f,$i,3),"d","w");

if ($as=='Y')
{
     $a[]=$n;
$n=$n+1;
     $a[]=convert_cyr_string(mysql_result($f,$i,0),"d","w");
     $a[]=convert_cyr_string(mysql_result($f,$i,1),"d","w");

     $c=convert_cyr_string(mysql_result($f,$i,1),"d","w");
     $c2=$c/100*$skid;
     $c=$c-$c2;

//Округление до сотых
$c=$c*100;
$c=round($c)/100;

     $a[]=$c;
     $a[]=convert_cyr_string(mysql_result($f,$i,2),"d","w");
     
     if (count($a)<2) continue; // если она пустая (глюки), пропускаем
     echo "<tr ALIGN=center>";
     // цикл вывода всех колонок текущей строки таблицы
     for ($j=0; $j<$x; $j++) 
     {
         // если ячейка пустая, там надо поместить "&nbsp;";
         if (strlen($a[$j])==0) echo "<td BGCOLOR=$coltab>&nbsp;</td>";
         else echo "<td BGCOLOR=$coltab>$a[$j]</td>";
     }
     // рисуем колонку просмотр
     echo "<td BGCOLOR=$coltab>".
          "<a href=?c=view&SID=$SID&n=$i>Просмотр</a></td>";


     //если нет на складе, то не выводить checkbox
     if (convert_cyr_string(mysql_result($f,$i,2),"d","w")<1)
     {
        echo "<td BGCOLOR=$coltab>&nbsp;</td>";
     }
     else // рисуем checkbox 
     {           
        echo "<td BGCOLOR=$coltab><input type=checkbox name=v[$i] value=$i></td>";
     }
     echo "</tr>";
     unset($a);
}
   }
   echo "</table><input type=submit value='Добавить ".
        "в корзину'  ></form></center>"; 
   mysql_close();
}
//-------------

/* Выводит на экран несколько чисел (написано). Подсчет значений происходит
   при каджом вызове.   */

//-------------
function summa() 
{
   global $t ,$col,$summ, $sm;
   global $hostname, $username, $password, $dbName, $skid, $summ2;
   echo"<BODY BGCOLOR=$col>";
   // традиционный проход массива товаров из корзины
   $k=@array_keys($t[all]);
   $summ2=0; 
   for ($i=0; $i<count($k); $i++) 
   {
      $id=$k[$i];
      
      $summ+=(double)$t[$id][kol]* (double)$t[$id][cena];
      $summ2+=$t[$id][kol];
   }

   $usertable="skid";
   mysql_connect($hostname,$username,$password) OR DIE("Не могу создать соединение ");
   mysql_select_db("$dbName") or die("Не могу выбрать базу данных "); 
   $q="select * from $usertable";
   $r=mysql_query($q);
   $kl=mysql_num_rows($r);
   $skid=0;
   for ($j=0; $j<$kl; $j++)
   {
      $svishe=convert_cyr_string(mysql_result($r,$j,1),"w","d");
      $sk=convert_cyr_string(mysql_result($r,$j,2),"w","d");
      if ($summ>$svishe) $skid=$sk;
   }
   $su=$summ/100*$skid;
   $sm=$summ-$su;

//Округление до сотых
$sm=$sm*100;
$sm=round($sm)/100;

   $usertable = "tovar";

   // просто выводим посчитанные цифры на экран
   echo "<center><FONT color=black> ".
        "Выбраных товаров: <FONT color=red>$i</FONT> шт.".
        " Общее количество: <FONT color=red>$summ2</FONT> шт. Сумма: ".
        sprintf("<FONT color=red>%.2f</FONT> руб.",$summ).
        " Скидка: <FONT color=red>$skid</font> %".
        " Сумма (со скидкой): ".
        sprintf("<FONT color=red>%.2f</FONT> руб.",$sm).
        "</FONT><hr color=blue></center>";
   mysql_close();
}
//-------------


// добавление данных в таблицы
//-------------
function dvBD() 
{
   global $v, $t;
   global $hostname, $username, $password, $dbName;
   $usertable = "pokup";
   /* создать соединение */
   mysql_connect($hostname,$username,$password) OR DIE("Не могу создать соединение ");
   mysql_select_db("$dbName") or die("Не могу выбрать базу данных "); 
 
   for ($j=0; $j<19; $j++)
   {
      $Dv[]=convert_cyr_string($v[$j],"w","d");
   }

   /* Вставить информацию о клиенте в таблицу pokup*/
   $query="INSERT INTO $usertable set naim_org='$Dv[0]',".
          "fam='$Dv[1]',imya='$Dv[2]',otch='$Dv[3]',yur_adress='$Dv[4]',".
          "fak_adress='$Dv[5]',inn='$Dv[6]',tel='$Dv[7]',email='$Dv[8]'";
   $result = mysql_query($query);

   $q="select id from $usertable";
   $r=mysql_query($q);
   $n2=mysql_num_rows($r);
   $num=convert_cyr_string(mysql_result($r,$n2-1,0),"d","w");


   $k=@array_keys($t[all]);
   for ($i=0; $i<count($k); $i++) 
   {
      $id=$k[$i];        
      $sum=(double)$t[$id][cena]*(double)$t[$id][kol];
      $sum2+=$sum;
   }

   $timeT=getdate();
   $dt=$timeT[year].".".$timeT[mon].".".$timeT[mday];
   $tm=$timeT[hours].":".$timeT[minutes].":".$timeT[seconds];  

   $usertable = "skid";
   $query="select * from $usertable";
   $r=mysql_query($query);
   $kl=mysql_num_rows($r);
   for ($i=0; $i<$kl; $i++)
   {
      $svishe=convert_cyr_string(mysql_result($r,$i,1),"d","w");
      $sk=convert_cyr_string(mysql_result($r,$i,2),"d","w");
      if ($sum2>$svishe) $skid=$sk;
   }

   $S2=(double)$sum2/100*(double)$skid;
   $S2=$sum2-$S2;

   $dtd.=$Dv[12].".".$Dv[11].".".$Dv[10];
   $tmot.=$Dv[13].":".$Dv[14].":00";
   $tmdo.=$Dv[15].":".$Dv[16].":00";

   $usertable = "zakaz";
   /* Вставить информацию о заказе в таблицу zakaz*/
   $query="INSERT INTO $usertable set id_pok='$num',".
          "date='$dt', time='$tm', itogo='$sum2', itogo_skid='$S2',".
          "adress_dost='$Dv[9]', date_dost='$dtd', time_ot='$tmot',".
          " time_do='$tmdo', dost='N'";
   $result = mysql_query($query);

   $q="select id from $usertable";
   $r=mysql_query($q);
   $n2=mysql_num_rows($r);
   $num2=convert_cyr_string(mysql_result($r,$n2-1,0),"d","w");


   $usertable = "dopoln";

   $k=@array_keys($t[all]);
   for ($i=0; $i<count($k); $i++) 
   {
      $id=$k[$i];        
      $sum=(double)$t[$id][cena]*(double)$t[$id][kol];
      $sum2+=$sum;
      $cen_sk=$t[$id][cena]/100*$skid;
      $cen_sk=$t[$id][cena]-$cen_sk;
      $sum_sk=$cen_sk*$t[$id][kol];
      $it_sk+=$sum_sk;
      $kol=$t[$id][kol];
      /* Вставить информацию в таблицу dopoln*/
      $query="INSERT INTO $usertable set id_zak='$num2',".
             "id_tov='$id',kol_tov='$kol', summa='$sum', skid='$skid'";
      $result = mysql_query($query);
   }   
   $usertable = "zakaz";
   /* Вставить информацию о заказе в таблицу zakaz*/
   $query="INSERT INTO $usertable set itogo_skid='$it_sk' where id='$num2'";
   $result = mysql_query($query);

   $usertable = "tovar";

   $k=@array_keys($t[all]);
   for ($i=0; $i<count($k); $i++) 
   {
      $id=$k[$i];        
      $kol=$t[$id][kol];

      $query="select kol_vo from $usertable where id=$id";
      $result=mysql_query($query);
      $kolich=mysql_result($result,0,0);
      $kolich-=$kol;  
      $query="update $usertable set kol_vo='$kolich', rezerv='$kol' where id=$id";   
      $result=mysql_query($query);
   }

   unset($Dv);
   mysql_close();
}
//-------------



//-------------
function view($n)
{
   global $t, $hostname, $username, $password, $dbName, $usertable, $coltab;
   mysql_connect($hostname,$username,$password) or die ("Нет соединения с MySQL");
   mysql_select_db("$dbName")or die("Не могу выбрать базу данных ");
   $query="select info, pict from $usertable";
   $f=mysql_query($query);  
   $in=convert_cyr_string(mysql_result($f,$n,0),"d","w");
   $pict=mysql_result($f,$n,1);
   echo "<center><table border=2><tr><td bgcolor=$coltab>$in</td></tr></table></center>".
        "<br><center><table border=0><tr><td><IMG src=$pict></td></tr></table></center><br>"; 
   mysql_close();
}
//-------------


$post=array(
       "Наименование организации",
       "Фамилия",
       "Имя",
       "Отчество",      
       "Юридический адрес",
       "Фактический адрес",
       "ИНН",
       "Контактный телефон",
       "E-mail");
$ogl=array(
       "№",
       "Наименование",
       "Цена(в руб)",
       "Цена со скидкой(в руб)",
       "На складе");
$hostname = "localhost";
$username = "root";
$password = "****";
$dbName = "shop";
$usertable="tovar";
$coltab='#eeeedd';
$col='#eeeeee';


//--------------------------------------------------//
//------------- основной код модуля shop -----------//
//--------------------------------------------------//

// $c - основная переменная, указывающая на нужное действие
if (!isset($c)) 
{
   $c='';
   // Очистка массива $t
   $k=@array_keys($t[all]);
   for ($i=0; $i<count($k); $i++) 
   {
      unset($t[$k[$i]]);
      unset($t[all][$k[$i]]);
   }
}

switch($c) 
{

   // без параметров - рисуем прайс-лист
   case "":   
      echo "<TITLE>Интернет магазин</TITLE>";
      summa(); // статистика по корзине
      echo "<center><FONT color=red size=5>Каталог</FONT></center>";
      echo "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;".
           "<a href='\'>Главная страница</a>&nbsp;&nbsp;</td></table>";      
      price(); // прайс      
   break;

   case "katal":   
      echo "<TITLE>Интернет магазин</TITLE>";
      summa(); // статистика по корзине
      echo "<center><FONT color=red size=5>Каталог</FONT></center>";
      echo "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;".
           "<a href='\'>Главная страница</a>&nbsp;&nbsp;</td>";  
      // ссылка для перехода на корзину
      echo "<td BGCOLOR=$coltab>&nbsp;&nbsp;<a href='$PHP_SELF?c=korzina&SID=$SID'>".
           "Просмотреть корзину</a></td></table>";
      price(); // прайс      
   break;

   // вывод корзины
   case "korzina":
      echo "<TITLE>Корзина</TITLE>";
      summa();
      echo "<center><FONT color=blue size=5>Корзина:</FONT></center>";
      echo "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href='\'>Главная страница</a>".
           "&nbsp;&nbsp;<td BGCOLOR=$coltab>&nbsp;&nbsp;".
           "<a href='$PHP_SELF?c=katal&SID=$SID'>Каталог товаров</a>&nbsp;&nbsp;</td></table>";
      korzina(); // рисуем таблицу корзины           
   break;


   // добавление из формы прайса всех товаров
   case "add":  
      // в массиве $v скоплены номера строк товаров, которые функция ...
      $k=@array_keys($v);
      for ($i=0; $i<count($k); $i++) 
      {
         // ... tadd() преобразует из файла в данные и поместит в сессии
         tadd($v[$k[$i]]);
      }
      // надо перенаправить браузер на приличный адрес, чтобы:
      // 1) в URL был написан приличный адрес
      // 2) чтобы не было глюка, если посетитель нажмет ОБНОВИТЬ СТРАНИЦУ
      exit(header("Location: $PHP_SELF?c=korzina&SID=$SID"));      
   break;


   // измение кол-ва товаров
   case "kolvo":
      // когда на странице КОРЗИНА нажимают СОХРАНИТЬ
      // ИЗМЕНЕНИЯ или ОФОРМИТЬ ЗАКАЗ..

      $k=@array_keys($v);
      for ($i=0; $i<count($k); $i++) 
      {
         $t[$k[$i]][kol]=abs(intval($v[$k[$i]]));
         if ($t[$k[$i]][kol]>$t[$k[$i]][sklad]) $t[$k[$i]][kol]=$t[$k[$i]][sklad];
      }
      // после изменения переенной сессии ее нужно записать
      session_register("t");

      // Далее важная проверка. Если посетитель нажимает кнопку СОХРАНИТЬ, то
      // у нас устанавливается переменная $edit, которая содержит строку
      // "Сохранить изменения". Если он нажимает ЗАКАЗ, то устанавливается
      // $zakaz. Устанавливается только одна из этих твух переменных.
      // если это было ИЗМЕНИТЬ, то переправить на корзину
      if (isset($edit)) exit(header("Location: $PHP_SELF?c=korzina&SID=$SID"));
      // иначе переправить на страницу с офрмлением заказа
      if (isset($zakaz))exit(header("Location: $PHP_SELF?c=zakaz&SID=$SID"));      
   break;


   // удаление товара по его $id
   case "del":
      $id=intval($id);
      unset($t[$id]);
      unset($t[all][$id]);
      session_register("t");
      exit(header("Location: $PHP_SELF?c=korzina&SID=$SID"));
   break;


   // удаление всей корзины
   case "delete":
      // Так же как и в пред. пункте, только с проходом
      // массива id товаров

      $k=@array_keys($t[all]);
      for ($i=0; $i<count($k); $i++) 
      {
         unset($t[$k[$i]]);
         unset($t[all][$k[$i]]);
      }
      session_register("t");
      exit(header("Location: $PHP_SELF?c=korzina&SID=$SID"));
   break;


   // форма для оформления заказа
   case "zakaz":
      //summa();
      echo "<TITLE>Анкета</TITLE>".
           "<BODY BGCOLOR=$col><center><FONT color=green size=5>Анкета</FONT></center>".
           "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;<a href='\'>Главная страница</a>".
           "&nbsp;&nbsp;<td BGCOLOR=$coltab>&nbsp;&nbsp;".
           "<a href='$PHP_SELF?c=korzina&SID=$SID'>Вернуться к корзине</a>&nbsp;&nbsp;</td></table>".
           "<center><form action='$PHP_SELF?c=post&SID=$SID' method=post>".
           "<table border=1>";
      for ($i=0; $i<count($post); $i++) 
      {
         echo "<tr><td BGCOLOR=$coltab>$post[$i]</td>".
              "<td><input type=text size=32 name='v[$i]'></td></tr>";
      }
      echo "</table>";
      echo "<table border=1>".
           "<tr><td>Адрес доставки</td>".
           "<td><input type=text size=32 name='v[$i]'></td></tr>".
           "</table>";
      $i++;

      echo "<table border=1>";
      echo "<tr><td>Дата доставки</td>".
           "<td><input type=text size=1 name='v[$i]'></td>";   
      $i++;
      echo "<td><input type=text size=1 name='v[$i]'></td>";
      $i++;
      echo "<td><input type=text size=1 name='v[$i]'></td>".
           "</tr></table>";
      echo "<table border=1>";
      $i++;
      echo "<tr><td>Время:     с</td>".
           "<td><input type=text size=1 name='v[$i]'></td>";
      $i++;
      echo "<td><input type=text size=1 name='v[$i]'></td>";     
           "</tr>";
      $i++;
      echo "<tr><td>Время:     до</td>".
           "<td><input type=text size=1 name='v[$i]'></td>";
      $i++;
      echo "<td><input type=text size=1 name='v[$i]'></td>".      
           "</tr></table><br>";

      echo "<input type=submit value='Отправить заказ'>".
           "</form></center>";           
   break;


   case "post":
      dvBD();
      exit(header("Location: $PHP_SELF?c=anketa&SID=$SID"));
   break;


   case "view":
      echo "<TITLE>Данные о товаре</TITLE>";    
      echo"<BODY BGCOLOR=$col>";  
      echo "<FONT color=blue size=5>Просмотр товара:</FONT><br><br>";
      echo "<table border=1><td BGCOLOR=$coltab>&nbsp;&nbsp;".
           "<a href='\'>Главная страница</a>&nbsp;&nbsp;</td>".
           "<td BGCOLOR=$coltab>&nbsp;&nbsp;".
           "<a href='$PHP_SELF?c=katal&SID=$SID'>Катоалог товаров</a>".
           "&nbsp;&nbsp;</td></table>";
      view($n);            
   break;


   case "anketa":     
      echo "<BODY BGCOLOR=$col>".
           "<table width=100% height=95%><tr><td align=center>".
           "<h2>Ваш заказ отправлен!<br>".
           "Спасибо за покупку!</h2>".
           "<hr width=60%><br>".
           "<a href='/'>Главная страница</a><br><br>".
           "<a href='".$PHP_SELF."'>Каталог товаров</a>".
           "</tD></tr></table>";
  
  
      $msg="Анкета посетителя:\n\n";
      for ($i=0; $i<count($post); $i++) 
      {
         $msg.="$post[$i]: ".substr($v[$i],0,500)."\n";
      }
      $msg.="\nСписок покупок:\n\n";
      $k=@array_keys($t[all]);
      for ($i=0; $i<count($k); $i++) 
      {
         $id=$k[$i];
         $msg.=($i+1).") {$t[$id][name]} \\ ".doubleval($t[$id][cena]).
               " руб \\ {$t[$id][kol]} шт. \\ = ".
               sprintf("%.2f",$t[$id][cena]*$t[$id][kol])." руб\n";
      }   
      $timeT=getdate();
      $msg.="\n\nДата заказа:   ".$timeT[mday].
            ".".$timeT[mon].".".$timeT[year]."г.";
      $msg.="\nВремя заказа:  ".$timeT[hours].
            ":".$timeT[minutes].":".$timeT[seconds];         
    
      echo "<br><br><br><pre>".$msg."</pre>"; 
   break;

}  

?>
